### ISSUE TITLE
tobs install failure on gcp 

### ISSUE THREAD

**Issue by dnck** [timescale/tobs#169]
With the kubeconfig 

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: OMIT 
    server: OMIT
  name: OMIT
contexts:
- context:
    cluster: OMIT
    namespace: OMIT
    user: OMIT
  name: OMIT
current-context: OMIT
kind: Config
preferences: {}
users:
- name: OMIT
  user:
    auth-provider:
      config:
        access-token: OMIT
        cmd-args: config config-helper --format=json
        cmd-path: gcloud
        expiry: "2021-09-22T14:53:32Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

Running, 

```
./tobs install --chart-reference ../chart
```

from the `cli` directory fails, 

```
... no Auth Provider found for name "gcp"
```

This seems to be a regression to https://github.com/timescale/tobs/issues/68.
