### ISSUE TITLE
Helm fails when deploying a remote observer cluster

### ISSUE THREAD

**Issue by SteveMaddison** [timescale/tobs#181]
Following the steps [here](https://github.com/timescale/tobs/blob/master/chart/docs/values-config.md#deploying-the-observer-cluster) to deploy an observer cluster, Helm is unable to render `NOTES.txt` due to `template "timescaledb.fullname"` (lines 123, 126) and `template "clusterName"` (lines 140, 146) not being defined. I suspect the entire section on TimescaleDB isn't relevant could actually be if-ed out in this situation.

Sanitized values to reproduce:
```
timescaledb-single:
  enabled: false
promscale:
  enabled: false
kube-prometheus-stack:
  grafana:
    enabled: false
kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      externalLabels:
        cluster: mycluster  
      remoteRead:
      - url: http://promscale.example.com/read
        readRecent: true
      remoteWrite:
      - url: http://promscale.example.com/write
```
