### ISSUE TITLE
Unable to install tobs due to cert-manager dependency

### ISSUE THREAD

**Issue by zcourts** [timescale/tobs#197]
Trying to install tobs into a new 1.22 cluster.
I've set `promscale.tracing.enabled = false` but the install still tries to create cert-manager types. We can't install cert-manager as it conflicts with our own PKI. Would also not work in customer environments if we asked them to install it because most of them also don't have cert-manager.

Snipper of values.yaml

```
      promscale:
        enabled: true
        image: timescale/promscale:0.6.1
        # DISABLED - requires, deploys OpenTelemetry Operator which then insanely requires cert-manager
        tracing:
          enabled: false
        # by default Promscale isn't configured to accept traces
        # to enable pass below arg
        args: []
#         - "-otlp-grpc-server-listen-address=:9202"
```

The resulting error is:
```
Error: unable to build kubernetes objects from release manifest: [unable to recognize \"\": no matches for kind \"Certificate\" in version \"cert-manager.io/v1alpha2\", unable to recognize \"\": no matches for kind \"Issuer\" in version \"cert-manager.io/v1alpha2\"]
```
The `\` are because I'm using the ansible Helm module and this is being installed as part of a tobs ansible role I've written.

**Comment by zcourts** [comment]
Can Tobs not use https://github.com/open-telemetry/opentelemetry-collector directly? It has no dependency on cert-manager from what I can see https://github.com/open-telemetry/opentelemetry-collector/search?q=cert-manager&type=code - only the operator does.

**Comment by VineethReddy02** [comment]
@zcourts 

1. Can you share the cmds and steps you are using to deploy tobs?
2. Today tobs uses otel-operator (which internally is dependent on the cert-manager) to deploy otel-collector. So to deploy otel-collector with tobs you definitely need otel-operator. 
3. By default otel components are disabled in tobs. To enable you either use `--tracing` flag with tobs CLI cmd or enable it in tobs `values.yaml`. 
4. The snippet you shared above from`values.yaml` i.e.
```
      promscale:
        enabled: true
        image: timescale/promscale:0.6.1
        # DISABLED - requires, deploys OpenTelemetry Operator which then insanely requires cert-manager
        tracing:
          enabled: false
```
This only disables tracing port exposition in Promscale. To disable tracing components in tobs you have to use
```
# Enable OpenTelemetry Operator
# If using tobs CLI you can enable otel with --tracing flag
opentelemetryOperator:
  enabled: false
```
FYI, By default otel is disabled in tobs.
