### ISSUE TITLE
OpenTelemetry auto-instrumentation with tobs

### ISSUE THREAD

**Issue by VineethReddy02** [timescale/tobs#224]
With the recent release of tobs we support OpenTelemetry operator version `0.41.1` which includes auto-instrumentation support for

1. Java
2. Nodejs
3. Python

Create the instrumentation CR as

```
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: java
spec:
  exporter:
    endpoint: http://localhost:4317
  propagators:
    - jaeger
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
```

Enable auto-instrumentation to Java container by adding the below annotations to your deployment as
```
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-java: "true"
```

This task is to improve the user experience of auto-instrumentation support for tobs. 

1. Create the instrumentation CR by default when `--tracing` is enabled. And make sure to add steps of podAnnotations in the install success message.  
2. Let users know how easy it is to add auto-instrumentation for existing applications without code changes. By adding the steps in docs for easier understanding and getting started guide for auto-inst.
3. Also, update the `tracing.md` in the Promscale repo about auto-instrumentation support and how to leverage it.
