### ISSUE TITLE
Drop setting db-password explicitly for Promscale conn details during helm install

### ISSUE THREAD

**Issue by VineethReddy02** [timescale/tobs#244]
Currently, the helm-chart installation requires 

```
helm install <release_name> timescale/tobs promscale.connection.password=<password> 
```

password to be explicitly configured. We should get rid of this by setting the database password on installation.
This shouldn’t involve writing a new logic. But like testing passwords by configuring for timescaledb-single helm chart and referencing them in Promscale (in connection details) and Kube-Prometheus helm chart (for Grafana DB job to access database)

**Comment by paulfantom** [comment]
To satisfy GitOps requirement I propose to move execution of this task into the cluster and out of tobs binary. My proposal is to do the following:
- Use timescaledb helm chart to generate secrets
- Inject a kubernetes Job that picks up timescaledb credentials and connection parameters and dynamically creates promscale secret from those

Such Job should be conditionally included if user did not provide database connection parameters.

**Comment by politician** [comment]
Sharing this here in case that's of any help for someone

```yaml
{{- $tobsSecretName := printf "%s-credentials" .Release.Name }}

{{- $tobsReplicaPwd := (randAlpha 16) | b64enc | quote }}
{{- $tobsSuPwd := (randAlpha 16) | b64enc | quote }}
{{- $tobsAdminPwd := (randAlpha 16) | b64enc | quote }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace $tobsSecretName) }}
{{- if $secret }}
{{- $tobsReplicaPwd = index $secret.data "PATRONI_REPLICATION_PASSWORD" }}
{{- $tobsSuPwd = index $secret.data "PATRONI_SUPERUSER_PASSWORD" }}
{{- $tobsAdminPwd = index $secret.data "PATRONI_admin_PASSWORD" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name:  {{ $tobsSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-timescaledb
    cluster-name: {{ .Release.Name }}
type: Opaque
data:
  PATRONI_REPLICATION_PASSWORD: {{ $tobsReplicaPwd}}
  PATRONI_SUPERUSER_PASSWORD: {{ $tobsSuPwd}}
  PATRONI_admin_PASSWORD: {{ $tobsAdminPwd}}
```
