### ISSUE TITLE
Cert-manager pods are not scraped

### ISSUE THREAD

**Issue by paulfantom** [timescale/tobs#355]
**What happened?**

There is no metrics data from cert-manager pods

**Did you expect to see something different?**

Data being collected

**How to reproduce it (as minimally and precisely as possible)**:

Do a helm install

**Environment**

* tobs installation method:

- [x] cli
- [x] helm chart

* tobs version:

    0.10.0-alpha

* Kubernetes version information:

1.23

* Kubernetes cluster kind:

`kind`

**Anything else we need to know?**:

cert-manager pods live in `cert-manager` namespace and do have following annotations:
```
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9402"
    prometheus.io/scrape: "true"
```

Which means that configuration shipped with tobs to allow annotation-based scraping should pick them up.
