### ISSUE TITLE
add tolerations affinity

### ISSUE THREAD

**Issue by ronaldo-barros** [timescale/tobs#383]
add options tolerations and affinity in deploy

**Comment by paulfantom** [comment]
Could you specify which components you want to have tolerations and affinity? I am asking because many of them already have that option.

**Comment by theelderbeever** [comment]
The Node Exporter could use tolerations. I often time taint nodes for databases and the like but still want the node exporters to tolerate all taints so I can still watch them.

As for affinities I think the answer is that all of the stack needs affinity capability. Along similar lines as above I might want to launch the observability backing timescale instance to a dedicated node and likewise might have dedicated nodes for the rest of the observability stack (sans exporters) so that I can sequester them from the rest of the production pods that I may have running.

**Comment by paulfantom** [comment]
> The Node Exporter could use tolerations

This option already exists as it is included in node-exporter helm chart. By default it is set to https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml#L160-L162

In tobs it is possible to access this setting via:
```yaml
kube-prometheus-stack:
  prometheus-node-exporter:
    tolerations:
      - effect: NoSchedule
        operator: Exists
```

---
> As for affinities I think the answer is that all of the stack needs affinity capability.

I think that the components in the stack already have this capability. For example node-exporter affinity is available via:
```yaml
kube-prometheus-stack:
  prometheus-node-exporter:
    affinity: {}
```
Another example would be promscale for which affinities can be set via:
```yaml
promscale:
  affinity: {}
```

---

Considering the above my question from https://github.com/timescale/tobs/issues/383#issuecomment-1135573409 still stands.
