### ISSUE TITLE
An option to set `hostRootFsMount`?

### ISSUE THREAD

**Issue by MPThLee** [timescale/tobs#391]
**What did you do?**
Installer hangs when I tried to install tobs on LXC-based k3s cluster.

**Did you expect to see some different?**
It should be installed. but seems like lxc and node-exporter has an issue

**Environment**
* tobs installation method: `cli`

* tobs version:

  `tobs version`

   `Tobs CLI Version: 0.10.0, latest tobs helm chart version: 0.10.1`

* Kubernetes version information:

  `kubectl version`

    ```
    Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", 
    GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", 
    GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
   Kustomize Version: v4.5.4
   Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", 
   GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"2022-04-28T22:16:18Z", 
   GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
   ```

* Kubernetes cluster kind:

  on LXC-based debian container, setup with k3sup.

* tobs Logs:

```
Couldn't find the cert-manager. The cert-manager is required to deploy OpenTelemetry. Do you want to install the cert-manager?
confirm the action by typing y or yes and press enter: y
Waiting on pod cert-manager-cainjector-8c7796555-jp4cc...
Pod cert-manager-cainjector-8c7796555-jp4cc has started
Waiting on pod cert-manager-cdc85d4c4-rt84n...
Pod cert-manager-cdc85d4c4-rt84n has started
Waiting on pod cert-manager-webhook-55f45df998-lzs92...
Pod cert-manager-webhook-55f45df998-lzs92 has started
Successfully created cert-manager
Installing The Observability Stack, this can take a few minutes
Error: could not install The Observability Stack: could not install The Observability Stack: rate: Wait(n=1) would exceed context deadline
```

 * pods log:
from `tobs-prometheus-node-exporter-*`
```
  - image: quay.io/prometheus/node-exporter:v1.3.1
    imageID: ""
    lastState: {}
    name: node-exporter
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: 'failed to generate container "bd5701c0aaab5a94ededec0dd0ce6036f1c87c8dfeb67ec2597b8f4bdce39682"
          spec: failed to generate spec: path "/" is mounted on "/" but it is not
          a shared or slave mount'
        reason: CreateContainerError
```
**Anything else we need to know?**:
Seems like it's same issue as this: https://github.com/prometheus-community/helm-charts/issues/467

they added an option `hostRootFsMount` to solve this issue.

**Comment by paulfantom** [comment]
This should be already possible by setting the following config in `values.yaml`:
```
kube-prometheus-stack:
  prometheus-node-exporter:
    hostRootFsMount:
      enabled: false
```
