### ISSUE TITLE
Include Promscale recommended Prometheus config by default

### ISSUE THREAD

**Issue by VineethReddy02** [timescale/tobs#578]
**What happened?**
Tobs doesn't include the recommended Prometheus `remote-write` configuration by default. 

**Did you expect to see something different?**
As default remote storage system for Prometheus is Promscale, include [recommended](https://docs.timescale.com/promscale/latest/recommendations/resource-recomm/#prometheus-remote-write) Prometheus remote-write config.

**How to reproduce it (as minimally and precisely as possible)**:

Default tobs installation

**Anything else we need to know?**:

The recommended Prometheus config, that should be added by default in `values.yaml`

```
remote_write:
  remote_timeout: 100s
  queue_config:
    capacity: 100000
    max_samples_per_second: 10000
    batch_send_deadline: 30s
    min_shards: 20
    max_shards: 20
    min_backoff: 100ms
    max_backoff: 10s
```
