### ISSUE TITLE
tobs install error on GKE

### ISSUE THREAD

**Issue by tuapuikia** [timescale/tobs#68]
Hi,

I created a new GKE cluster and tried to deploy Promscale using Tobs. But after the installation, the process exit with the following error message.

`$>tobs install`
Adding Timescale Helm Repository
"timescale" has been added to your repositories
Fetching updates from repository
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "timescale" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
Installing The Observability Stack
Waiting for pods to initialize...
2020/10/08 15:26:36 no Auth Provider found for name "gcp"

`$>tobs grafana get-password`
2020/10/08 15:30:20 no Auth Provider found for name "gcp"

kubeconf context

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://XXX.XXX.XXX.XXX
  name: gke_cluster
contexts:
- context:
    cluster: gke_cluster
    user: gke_cluster
  name: gke_cluster
current-context: gke_cluster
kind: Config
preferences: {}
users:
- name: gke_cluster
  user:
    auth-provider:
      config:
        access-token: OMITTED
        cmd-args: config config-helper --format=json
        cmd-path: gcloud
        expiry: "2020-10-08T08:17:55Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```
